### ISSUE TITLE
有个不明白的地方想请教一下.

### ISSUE THREAD

**Issue by weirantongxue** [beardlessCat/im#2]
1.集群情况下,其中的每一个server服务要别所有的server建立连接吧.集群项目启动的时候只能一个一个启动吧,如果同时启动会出现有的server和server之间的连接建立会漏掉.

2.横向扩容的时候也只能一台一台的扩容吧.

3.如果在消息发送的时候一台server突然挂掉了.那这个消息从client到server就失败了.消息就会丢掉.(这个可以从链路上做分段ack缓存失败的消息)

4.如果在消息发送的时候一台server突然挂掉了,已经到达当前server的消息就会丢失.

**Comment by beardlessCat** [comment]
1.就算两个server出现你说的那种同时启动的情况，他们在zk创建node触发的node新增事件也是有前有后。
2.不会出现第一种情况，扩容的台数也就无所谓了。但是我感觉要是集群的实例太多了，结合mq实现集群更合适一些。
3&4 当前写的就只是个案例，没有加消息的丢失和补偿机制，你说的这两种情况肯定会出现。

**Comment by weirantongxue** [comment]
晓得啦.感谢感谢.
